---
title: "Biostat 203B Homework 1"
subtitle: Due Jan 26, 2024 @ 11:59PM
author: "Puyuan Liu, 806152535"
format:
  html:
    theme: cosmo
    embed-resources: true
    number-sections: false
    toc: true
    toc-depth: 4
    toc-location: left
    code-fold: false
knitr:
  opts_chunk: 
    cache: false    
    echo: true
    fig.align: 'center'
    fig.width: 6
    fig.height: 4
    message: FALSE
---

Display machine information for reproducibility:

```{r}
#| eval: false
sessionInfo()
```

## Q1. Git/GitHub

**No handwritten homework reports are accepted for this course.** We work with Git and GitHub. Efficient and abundant use of Git, e.g., frequent and well-documented commits, is an important criterion for grading your homework.

1.  Apply for the [Student Developer Pack](https://education.github.com/pack) at GitHub using your UCLA email. You'll get GitHub Pro account for free (unlimited public and private repositories).

2.  Create a **private** repository `biostat-203b-2024-winter` and add `Hua-Zhou` and TA team (`Tomoki-Okuno` for Lec 1; `jonathanhori` and `jasenzhang1` for Lec 80) as your collaborators with write permission.

3.  Top directories of the repository should be `hw1`, `hw2`, ... Maintain two branches `main` and `develop`. The `develop` branch will be your main playground, the place where you develop solution (code) to homework problems and write up report. The `main` branch will be your presentation area. Submit your homework files (Quarto file `qmd`, `html` file converted by Quarto, all code and extra data sets to reproduce results) in the `main` branch.

4.  After each homework due date, course reader and instructor will check out your `main` branch for grading. Tag each of your homework submissions with tag names `hw1`, `hw2`, ... Tagging time will be used as your submission time. That means if you tag your `hw1` submission after deadline, penalty points will be deducted for late submission.

5.  After this course, you can make this repository public and use it to demonstrate your skill sets on job market.

## Q2. Data ethics training

This exercise (and later in this course) uses the [MIMIC-IV data v2.2](https://physionet.org/content/mimiciv/2.2/), a freely accessible critical care database developed by the MIT Lab for Computational Physiology. Follow the instructions at <https://mimic.mit.edu/docs/gettingstarted/> to (1) complete the CITI `Data or Specimens Only Research` course and (2) obtain the PhysioNet credential for using the MIMIC-IV data. Display the verification links to your completion report and completion certificate here. **You must complete Q2 before working on the remaining questions.** (Hint: The CITI training takes a few hours and the PhysioNet credentialing takes a couple days; do not leave it to the last minute.)

**Answer:** I completed the CITI training on Jan 16, 2024. The completion report is available at [here](https://www.citiprogram.org/verify/?k088f2190-93c7-417d-914a-ae93a804fffa-60560689). The completion certificate is available at [here](https://www.citiprogram.org/verify/?w9845cb74-2df6-467d-ad48-014d6f41f163-60560689).

## Q3. Linux Shell Commands

1.  Make the MIMIC v2.2 data available at location `~/mimic`.

Refer to the documentation <https://physionet.org/content/mimiciv/2.2/> for details of data files. Please, do **not** put these data files into Git; they are big. Do **not** copy them into your directory. Do **not** decompress the gz data files. These create unnecessary big files and are not big-data-friendly practices. Read from the data folder `~/mimic` directly in following exercises.

Use Bash commands to answer following questions.

**Answer:** I downloaded the MIMIC-IV data v2.2 to my local machine. The data files are available at `~/mimic`. The data files are not put into Git. The data files are not copied to my directory. The gz data files are not decompressed.

```{bash}
ls -l ~/mimic/
```

2.  Display the contents in the folders `hosp` and `icu` using Bash command `ls -l`. Why are these data files distributed as `.csv.gz` files instead of `.csv` (comma separated values) files? Read the page <https://mimic.mit.edu/docs/iv/> to understand what's in each folder.

**Answer** The data files are distributed as `.csv.gz` files instead of `.csv` files because the `.csv.gz` files are compressed, take less space, and use less internet bandwidth.

This is content of the `hosp` folder:

```{bash}
ls -l ~/mimic/hosp/
```

This is content of the `icu` folder:

```{bash}
ls -l ~/mimic/icu/
```

3.  Briefly describe what Bash commands `zcat`, `zless`, `zmore`, and `zgrep` do.

**Answer:**\
1). `zcat` is used to display the contents of a compressed file.\
2). `zless` allows to view the contents of compressed files page by page.\
3). `zgrep` is used to search for a pattern in compressed files. It works similarly to grep but on gzip-compressed files.\
4). `zmore` displays the contents of compressed files one screen at a time (screen by screen).\
5). `zgrep` is used to search for a pattern in compressed files.

4.  (Looping in Bash) What's the output of the following bash script?

```{bash}
#| eval: false
for datafile in ~/mimic/hosp/{a,l,pa}*.gz
do
  ls -l $datafile
done
```

Display the number of lines in each data file using a similar loop. (Hint: combine linux commands `zcat <` and `wc -l`.)

```{bash}
#| eval: false
for datafile in ~/mimic/hosp/{a,l,pa}*.gz
do
  zcat <$datafile | wc -l
done
```

5.  Display the first few lines of `admissions.csv.gz`. How many rows are in this data file? How many unique patients (identified by `subject_id`) are in this data file? Do they match the number of patients listed in the `patients.csv.gz` file? (Hint: combine Linux commands `zcat <`, `head`/`tail`, `awk`, `sort`, `uniq`, `wc`, and so on.)

```{bash}
# Display the first few lines of admissions.csv.gz
zcat <~/mimic/hosp/admissions.csv.gz | head
```

```{bash}
# Count the number of rows in admissions.csv.gz
zcat <~/mimic/hosp/admissions.csv.gz | wc -l
```

```{bash}
# Count the number of unique patients in admissions.csv.gz
zcat <~/mimic/hosp/admissions.csv.gz | awk -F, '{print $1}' | sort | uniq | wc -l
```

```{bash}
# Count the number of patients in patients.csv.gz
zcat <~/mimic/hosp/patients.csv.gz | wc -l
```

The mumber of unique patients in admissions.csc.gz does not match the number of patients listed in the `patients.csv.gz` file.

6.  What are the possible values taken by each of the variable `admission_type`, `admission_location`, `insurance`, and `ethnicity`? Also report the count for each unique value of these variables. (Hint: combine Linux commands `zcat`, `head`/`tail`, `awk`, `uniq -c`, `wc`, and so on; skip the header line.)

```{bash}
# possible values and counts taken by admission_type
zcat <~/mimic/hosp/admissions.csv.gz | tail -n +2 | awk -F',' '{print $6}' | sort | uniq -c
```

```{bash}
# possible values and counts taken by admission_location
zcat <~/mimic/hosp/admissions.csv.gz | tail -n +2 | awk -F',' '{print $8}' | sort | uniq -c
```

```{bash}
# possible values and counts taken by insurance
zcat <~/mimic/hosp/admissions.csv.gz | tail -n +2 | awk -F',' '{print $10}' | sort | uniq -c
```

```{bash}
# possible values and counts taken by race
zcat <~/mimic/hosp/admissions.csv.gz | tail -n +2 | awk -F',' '{print $13}' | sort | uniq -c
```

7.  *To compress, or not to compress. That's the question.* Let's focus on the big data file `labevents.csv.gz`. Compare compressed gz file size to the uncompressed file size. Compare the run times of `zcat < ~/mimic/labevents.csv.gz | wc -l` versus `wc -l labevents.csv`. Discuss the trade off between storage and speed for big data files. (Hint: `gzip -dk < FILENAME.gz > ./FILENAME`. Remember to delete the large `labevents.csv` file after the exercise.)

```{bash}
gzip -dkc ~/mimic/hosp/labevents.csv.gz > ~/labevents_uncompressed.csv
```

```{bash}
# Display the sizes of the compressed and uncompressed files
ls -lh ~/mimic/hosp/labevents.csv.gz

ls -lh ~/labevents_uncompressed.csv
```

```{bash}
# Run time for compressed file
time zcat < ~/mimic/hosp/labevents.csv.gz | wc -l
```

```{bash}
# Run time for uncompressed file
time wc -l ~/labevents_uncompressed.csv
```

**Answer:** The compressed gz file size is 1.9G. The uncompressed file size is 13G. The run time of `zcat < ~/mimic/labevents.csv.gz | wc -l` is 1 minute. The run time of `wc -l labevents.csv` is 9 seconds. The trade off between storage and speed for big data files is that the compressed gz file takes less space but takes more time to run. The uncompressed file takes more space but takes less time to run.

## Q4. Who's popular in Price and Prejudice

1.  You and your friend just have finished reading *Pride and Prejudice* by Jane Austen. Among the four main characters in the book, Elizabeth, Jane, Lydia, and Darcy, your friend thinks that Darcy was the most mentioned. You, however, are certain it was Elizabeth. Obtain the full text of the novel from <http://www.gutenberg.org/cache/epub/42671/pg42671.txt> and save to your local folder.

```{bash}
#| eval: false
wget -nc http://www.gutenberg.org/cache/epub/42671/pg42671.txt
```

Explain what `wget -nc` does. Do **not** put this text file `pg42671.txt` in Git.

Complete the following loop to tabulate the number of times each of the four characters is mentioned using Linux commands.

```{bash}
#| eval: false
for char in Elizabeth Jane Lydia Darcy
do
  echo $char:
  grep -o -i "$char" pg42671.txt | wc -l
done
```

Elizabeth is the most mentioned character in the book.

2.  What's the difference between the following two commands?

```{bash}
#| eval: false
echo 'hello, world' > test1.txt
```

and

```{bash}
#| eval: false
echo 'hello, world' >> test2.txt
```

**Answer**: the first command will overwrite the file `test1.txt` if it already exists. The second command will append the text to the end of the file `test2.txt` if it already exists.

3.  Using your favorite text editor (e.g., `vi`), type the following and save the file as `middle.sh`:

```{bash eval=FALSE}
#!/bin/sh
# Select lines from the middle of a file.
# Usage: bash middle.sh filename end_line num_lines
head -n "$2" "$1" | tail -n "$3"
```

Using `chmod` to make the file executable by the owner, and run

```{bash}
#| eval: false
chmod u+x middle.sh
./middle.sh pg42671.txt 20 5
```

Explain the output. Explain the meaning of `"$1"`, `"$2"`, and `"$3"` in this shell script. Why do we need the first line of the shell script?

**Answer**:

-   The output is the 5 lines from line 16 to line 20 of the file `pg42671.txt`.

-   `"$1"` is the first argument, `"$2"` is the second argument, and `"$3"` is the third argument, which means `"$1"`= pg42671.txt, `"$2"`= 20, and `"$3"`=5.

-   We need the first line of the shell script to tell the computer that this is a shell script. It also identifies the shell (bash,sh,csh, etc).


## Q5. More fun with Linux

Try following commands in Bash and interpret the results: `cal`, `cal 2024`, `cal 9 1752` (anything unusual?), `date`, `hostname`, `arch`, `uname -a`, `uptime`, `who am i`, `who`, `w`, `id`, `last | head`, `echo {con,pre}{sent,fer}{s,ed}`, `time sleep 5`, `history | tail`.

**Answer**

```{bash}
cal
```
`cal` shows the calendar for the current month. 

```{bash}
cal 2024
```
`cal 2024` shows the calendar for the year 2024.

```{bash}
cal 9 1752
```
`cal 9 1752` shows the calendar for the month of September in the year 1752. The calendar for September 1752 is unusual because the calendar was changed in September 1752. The calendar was changed from the Julian calendar to the Gregorian calendar. The Julian calendar was 11 days behind the Gregorian calendar. The calendar was changed in September 1752 by skipping 11 days. The 11 days skipped were September 3-13, 1752.

```{bash}
date
```
`date` shows the current date and time.


```{bash}
hostname
```
`hostname` shows the name of the computer.

```{bash}
arch
```
`arch` shows the architecture of the computer.

```{bash}
uname -a
```
`uname -a` shows the name of the computer, the version of the operating system, and the architecture of the computer.

```{bash}
uptime
```
`uptime` shows how long the computer has been running.

```{bash}
whoami
```
`whoami` shows the username of the current user.

```{bash}
who
```
`who` shows the users who are currently logged in.

```{bash}
w
```
`w` shows the users who are currently logged in and what they are doing.

```{bash}
id
```
`id` shows the user and group information for the current user.

```{bash}
last | head
```
`last | head` shows the last 10 users who logged in.

```{bash}
echo {con,pre}{sent,fer}{s,ed}
```
`echo {con,pre}{sent,fer}{s,ed}` shows the words that can be combined by the words `con` and `pre` with the words `sent` and `fer` with the words `s` and `ed`. The words that can be formed are `consents`, `conferred`, `presents`, `preferred`, `confered`, `conferes`, `confered`, `confered`, `presed`

```{bash}
time sleep 5
```
`time sleep 5` shows the time it takes to run the command `sleep 5`. The command `sleep 5` sleeps for 5 seconds.

```{bash}
history | tail
```
`history | tail` shows the last 10 commands that were run.

## Q6. Book

1.  Git clone the repository <https://github.com/christophergandrud/Rep-Res-Book> for the book *Reproducible Research with R and RStudio* to your local machine.

2.  Open the project by clicking `rep-res-3rd-edition.Rproj` and compile the book by clicking `Build Book` in the `Build` panel of RStudio. (Hint: I was able to build `git_book` and `epub_book` but not `pdf_book`.)

The point of this exercise is (1) to get the book for free and (2) to see an example how a complicated project such as a book can be organized in a reproducible way.

For grading purpose, include a screenshot of Section 4.1.5 of the book here.


