# Boosting

```{r}
library(tidyverse)
library(readr)
library(gtsummary)
library(tidymodels)
library(xgboost)
library(vip)
library(stacks)
```

```{r}
data_split <- readRDS("data_split.rds")
```

```{r}
icu_train <- training(data_split)
dim(icu_train)
```

```{r}
icu_test <- testing(data_split)
dim(icu_test)
```

```{r}
boost_recipe <- 
  recipe(
    los_long ~ ., 
    data = icu_train
  ) |>
  # mode imputation for categorical_var
  step_impute_mode(all_nominal_predictors()) |>
  # create traditional dummy variables (necessary for xgboost)
  step_dummy(all_nominal_predictors()) |>
  # zero-variance filter
  step_zv(all_numeric_predictors()) 
boost_recipe
```

```{r}
# Model
boost_mod <- 
  boost_tree(
    mode = "classification",
    trees = 400,
    tree_depth = tune(),
    learn_rate = tune()
  ) |> 
  set_engine("xgboost") 
boost_mod
```

```{r}
# Workflow
boost_wf <- workflow() |>
  add_recipe(boost_recipe) |>
  add_model(boost_mod)
boost_wf
```

```{r}
# Tuning grid
boost_param_grid <- grid_regular(
  tree_depth(range = c(2L, 3L)),
  learn_rate(range = c(-2, 0), trans = log10_trans()),
  levels = c(2, 5)
  )
boost_param_grid
```

```{r}
set.seed(203)

folds <- vfold_cv(icu_train, v = 3)
folds
```

```{r}
# Fit cross-validation (boosting)
set.seed(203)
if (file.exists("boost_fit.rds")) {
  boost_fit <- read_rds("boost_fit.rds")
} else {
  boost_fit <- boost_wf |>
    tune_grid(
      resamples = folds,
      grid = boost_param_grid,
      metrics = metric_set(roc_auc, accuracy),
      control = control_stack_grid()
      ) 
  write_rds(boost_fit, "boost_fit.rds")
}
boost_fit
```

```{r}
# Visualize CV results
boost_fit |>
  collect_metrics() |>
  print(width = Inf) |>
  filter(.metric == "roc_auc") |>
  ggplot(mapping = aes(x = learn_rate, y = mean, color = factor(tree_depth))) +
  geom_point() + 
  labs(x = "Learning Rate", y = "CV AUC") +
  scale_x_log10()
```

```{r}
# Show the best 5 model
boost_fit |>
  show_best("roc_auc")
```

```{r}
# Select the best model
best_boost <- boost_fit |>
  select_best("roc_auc")
best_boost
```

```{r}
# Final workflow
boost_final_wf <- boost_wf |>
  finalize_workflow(best_boost)
boost_final_wf
```

```{r}
# Fit the whole training set, then predict the test cases
if (file.exists("boost_final_fit.rds")) {
  boost_final_fit <- read_rds("boost_final_fit.rds")
} else {
  boost_final_fit <- boost_final_wf |>
    last_fit(data_split) |>
    write_rds("boost_final_fit.rds")
}
boost_final_fit
```

```{r}
# Test metrics
boost_final_fit |> 
  collect_metrics()
```

```{r}
# Extract important features
boost_features <- extract_fit_engine(boost_final_fit) |>
  vip(num_features = 6)
boost_features
```
