# Random Forest

```{r}
library(tidyverse)
library(readr)
library(gtsummary)
library(tidymodels)
library(ranger)
library(vip)
```

```{r}
data_split <- readRDS("data_split.rds")
```

```{r}
icu_train <- training(data_split)
dim(icu_train)
```

```{r}
icu_test <- testing(data_split)
dim(icu_test)
```

```{r}
rf_recipe <- 
  recipe(
    los_long ~ ., 
    data = icu_train
  ) |>
  # mode imputation for categorical_var
  step_impute_mode(all_nominal_predictors()) |>
  # zero-variance filter
  step_zv(all_numeric_predictors()) 
rf_recipe
```

```{r}
# Model
rf_mod <- 
  rand_forest(
    mode = "classification",
    # Number of predictors randomly sampled in each split
    mtry = tune(),
    # Number of trees in ensemble
    trees = tune()
  ) |> 
  set_engine("ranger", importance = "impurity") 
rf_mod
```

```{r}
# Workflow
rf_wf <- workflow() |>
  add_recipe(rf_recipe) |>
  add_model(rf_mod) 
rf_wf
```

```{r}
# Tuning grid
rf_param_grid <- grid_regular(
  trees(range = c(400L, 600L)), 
  mtry(range = c(1L, 3L)),
  levels = c(3, 3)
  )
rf_param_grid
```
```{r}
set.seed(203)

folds <- vfold_cv(icu_train, v = 4)
folds
```

```{r}
# Fit cross-validation (random forest)
set.seed(203)
(rf_fit <- rf_wf |>
  tune_grid(
    resamples = folds,
    grid = rf_param_grid,
    metrics = metric_set(roc_auc, accuracy)
    )) |>
  system.time()

rf_fit
```

```{r}
# Visualize CV results
rf_fit |>
  collect_metrics() |>
  print(width = Inf) |>
  filter(.metric == "roc_auc") |>
  ggplot(mapping = aes(x = trees, y = mean, color = factor(mtry))) +
  geom_point() + 
  labs(x = "Num. of Trees", y = "CV AUC")
```

```{r}
# Show the best 5 model
rf_fit |>
  show_best("roc_auc")
```

```{r}
# Select the best model
best_rf <- rf_fit |>
  select_best("roc_auc")
best_rf
```

```{r}
# Final workflow
rf_final_wf <- rf_wf |>
  finalize_workflow(best_rf)
rf_final_wf
```

```{r}
# Fit the whole training set, then predict the test cases
rf_final_fit <- 
  rf_final_wf |>
  last_fit(data_split)
rf_final_fit
```

```{r}
# Test metrics
rf_final_fit |> 
  collect_metrics()
```

```{r}
# Extract important features
rf_features <- extract_fit_engine(rf_final_fit) |>
  vip(num_features = 6)
rf_features
```

```{r save-workspace}
saveRDS(object = rf_wf, file = "rf_wf.rds")
saveRDS(object = rf_param_grid, file = "rf_param_grid.rds")
```
